export const products = [
  { id: 1, label: "Sample Product 1", value: 19.99,unit: "euro-br" },
  { id: 2, label: "Sample Product 2", value: 29.99,unit: "euro-br" },
  { id: 3, label: "Sample Product 3", value: 39.99,unit: "euro-kg" },
  { id: 4, label: "Sample Product 4", value: 39.99,unit: "euro-kg" },
  { id: 5, label: "Sample Product 5", value: 39.99,unit: "euro-br" },
  { id: 6, label: "Sample Product 6", value: 39.99,unit: "euro-kg" },
  { id: 7, label: "Sample Product 7", value: 39.99,unit: "euro-kg" },
  { id: 8, label: "Sample Product 8", value: 39.99,unit: "euro-br" },
  { id: 9, label: "Sample Product 9", value: 39.99,unit: "euro-kg" },
  { id: 10, label: "Sample Product 10", value: 39.99,unit: "euro-kg" },
  { id: 11, label: "Sample Product 11", value: 39.99,unit: "euro-br" },
  { id: 12, label: "Sample Product 12", value: 39.99,unit: "euro-kg" },
  { id: 13, label: "Sample Product 13", value: 39.99,unit: "euro-kg" },
  { id: 14, label: "Sample Product 14", value: 39.99,unit: "euro-br" },
  { id: 15, label: "Sample Product 15", value: 39.99,unit: "euro-kg" },
  { id: 16, label: "Sample Product 16", value: 39.99,unit: "euro-kg" },
  { id: 17, label: "Sample Product 17", value: 39.99,unit: "euro-br" },
  { id: 18, label: "Sample Product 18", value: 39.99,unit: "euro-kg" },
];
